version: 2.1

# reusable section using anchors and alias
defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

# reusable section using commands (function-like)
commands:
  print_pipeline_id:
    description: "this command prints pipeline id"
    parameters:
      id: 
        type: string
        default: $CIRCLE_WORKFLOW_ID
    steps: 
      - run: echo << parameters.id >>

jobs:
# simple shell commands
  print_hello:
    <<: *defaults
    steps:
      - run: "echo hello"

  print_world:
    <<: *defaults
    steps:
      - run: "echo world"
      
  project-info:
    <<: *defaults
    steps:
      - print_pipeline_id

#  Environment Variables
  print-name:
    <<: *defaults
    steps:
      - run: echo $name
  
  create-env-var:
    <<: *defaults
    steps:
      - run: echo 'export MY_ENV_VAR="FOO"' >> "$BASH_ENV"
      - run: echo $MY_ENV_VAR

#  Communicate Environment Variables between two jobs using work space(stay to 15 days)
  send-data:
    <<: *defaults
    steps:
      - run: echo "data to send" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths: 
            - output.txt
  receive-data:
    <<: *defaults
    steps:
      - attach_workspace:
         at: ~/
      - run: cat ~/output.txt

# on fail condition 
  failed-job:
    <<: *defaults
    steps:
      - run: return 1
      - run:
          name: failed job
          command: echo "JOB FAILED"
          when: on_fail

workflows:
  say-hello-workflow:
    jobs:
      - project-info
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print-name
      - create-env-var
      - send-data
      - receive-data:
          requires:
           - send-data
