version: 2.1
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: "echo hello"

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: "echo world"
      
  project-info:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "My pipeline id is << pipeline.id >> and my git branch is << pipeline.git.branch >>."  
#  Environment Variables
  print-name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo $name
  
  create-env-var:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: export MY_ENV_VAR="FOO" 
      - run: echo $MY_ENV_VAR

workflows:
  say-hello-workflow:
    jobs:
      - project-info
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print-name
      - create-env-var
